#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing and building your project before committing'

# Check and Fix Prettier standards / ESLint Standards
npx lint-staged

# Check units tests (Jest & React Testing)
npm test ||
(
    echo '🔬 ❌ Units Tests Check Failed. Run npm run test, add changes and try commit again.';
    false;
)

# If everything passes... Now we can commit
echo '🤔 ... Allright.... Code looks good to me... Trying to build now.'

npm run build ||
(
    echo '📦 ❌ Next build failed: View the errors above to see why.'
    false;
)

# If everything passes... Now we can commit
echo '✅ You win this time... I am committing this now.'